### ISSUE TITLE
"toggle-menu" only shows menu partially

### ISSUE THREAD

**Issue by pepperblue** [countvajhula/symex.el#10]
I'm not shure what is causing this but - at least in doom-emacs - setting `:verbosity` of hydra to `1` prevents the menu from being shown completely:
![hydra](https://user-images.githubusercontent.com/3543271/80374044-5756ce00-8896-11ea-8412-dc3b2a3d08ba.jpg)
Setting `:verbosity` to `2` solves this issue ...

**Comment by countvajhula** [comment]
I don't see a verbosity value of `2` documented anywhere, not sure how you figured that one out, nice work 😄. Looks like this works because of [this else clause](https://github.com/abo-abo/hydra/blob/87873d788891029d9e44fa5458321d6a05849b94/hydra.el#L960-L963) in Hydra. Seems like this uses `lv-message` instead of Emacs's built-in `message` to display the Hydra, which I guess must be handling a large hydra better in some way, going by [this docstring](https://github.com/abo-abo/hydra/blob/87873d788891029d9e44fa5458321d6a05849b94/lv.el#L24-L26). I will make the change to use it.

**Comment by pepperblue** [comment]
Many useful information is hidden in the issues :smile: 
Verbosity values are - for example - documented here:
https://github.com/abo-abo/hydra/issues/272 (post nr. 7 from abo-abo)
