### ISSUE TITLE
"Symbol's value as variable is void" for "symex-make-precaution" when compiling doom-emacs

### ISSUE THREAD

**Issue by pepperblue** [countvajhula/symex.el#16]
Function `symex-make-precaution` in file `symex-data.el` is declared using `cl-defun` without requiring `cl-lib`, causing "Symbols's value as variable is void" error compiling doom-emacs using emacs 27.1.
Adding `(require 'cl-lib)` in `symex-data.el` solves this for me ...

**Comment by pepperblue** [comment]
There is nearly no elisp-fu to me ;-) Researching on this topic I came acros the "feature" concept ... and regarding to this ... and as far as I understand ... it shouldn't be necessary to require `cl-lib` within `symex-data.el` ...
Possibly the problem is located in the compile process of doom-emacs ...

**Comment by countvajhula** [comment]
Hi @pepperblue . Thank you for the time you spent researching, very much appreciated. I think you're on the right track there, let's see if we can get to the bottom of it! I created two files locally to test this. One of them contains a `cl-defun` and the other just `require`s it:

**mod2.el**:
```
;(require 'cl-lib)

(cl-defun my-sample-func (arg &key k1)
  "A CL function."
  (let ((k1 (or k1 1)))
    (+ arg k1)))

(provide 'mod2)
```

**mod1.el**:
```
;(require 'cl-lib)

;; Add current directory to load path so require can find the source files
;; Adapted from:
;; https://github.com/Lindydancer/cmake-font-lock/blob/47687b6ccd0e244691fb5907aaba609e5a42d787/test/cmake-font-lock-test-setup.el#L20-L27
(defvar my-imports-test-directory
  (if load-file-name
      (file-name-directory load-file-name)
    default-directory))
(dolist (dir '("." ".."))
  (add-to-list 'load-path
               (concat my-imports-test-directory dir)))

(require 'mod2)

(message "All good!")
```

Note that both files contain a `(require 'cl-lib)` at the top that are commented out.

Running `emacs -Q` to get a vanilla emacs instance, and then calling `eval-buffer` on `mod1.el` results in the error:

`eval-buffer: Symbol’s function definition is void: cl-defun`

Now, uncommenting the `(require 'cl-lib)` in _either_ file (but not necessarily _both_) fixes the issue and prints `All good!`.

So this tells us that as long as the feature is loaded before the `cl-defun` statement is encountered -- whether it is loaded in the module itself or in the requiring module -- it does not complain.

I also tried installing it in Doom Emacs by following [this example](https://github.com/hlissner/doom-emacs/issues/1773#issuecomment-530647771), i.e. by adding this to `~/.doom.d/packages.el`:

```
(package! symex)
```

... and this in `~/.doom.d/config.el`:

```
(use-package! symex
  :config
  (global-set-key (kbd "s-;") 'symex-mode-interface)  ; or whatever keybinding you like
  (dolist (mode-name symex-lisp-modes)
    (let ((mode-hook (intern (concat (symbol-name mode-name)
                                     "-hook"))))
      (add-hook mode-hook 'symex-mode)))
  (symex-hide-menu))
```

and then ran `doom sync` which successfully installed the package.
`doom build` rebuilt all the packages without any errors too.

I'm not too familiar with Doom Emacs, so let me know if you followed a different process.

I wouldn't mind including `(require 'cl-lib)` in symex-data.el as a fix.  But if this is a real problem, I'd prefer to be able to reproduce it first before fixing it, so that we can ensure it doesn't happen in the future.

The only other thing I can think of at the moment is that somewhere in your config, you may be loading `symex-data.el` (or another such module) directly, before loading `symex.el`.

**Comment by pepperblue** [comment]
Hello @countvajhula. Thank you for your effort. I think it's a "special case" on my side, that possibly is related to my usage of Chemacs - I also wasn't able to reproduce the error on another machine where I'm using doom-emacs without Chemacs ...
So far I don't think there's anything to do on your side ... and sorry for the noise :-)

**Comment by countvajhula** [comment]
Not at all, I'm glad you brought this up. I find it kind of weird that modules that depend on certain modules work even if those imports are missing, as long as the import order loads those dependencies before this module is loaded. I guess this may be one aspect of "dynamic binding" in Emacs Lisp, but I wasn't able to find any specific docs about this besides those about "features" that you mentioned.

I've gone ahead and added explicit `(require 'cl-lib)` statements in all files using `cl-defun`. I don't have a way to reproduce this on my end but sounds like your Chemacs setup is stricter about explicit imports, so please let me know if this fixes the issue for you, or if it shows any other errors.

**Comment by pepperblue** [comment]
I have no idea, in which way Chemacs could be more "strict" ;-)
It's definitely working this way! Thank you for the fix/workaroud :-)
