### ISSUE TITLE
add demo gifs

### ISSUE THREAD

**Issue by tommy-mor** [countvajhula/symex.el#22]
something like the gifs at
https://shaunlebron.github.io/parinfer/

I made this video: 
https://www.reddit.com/r/emacs/comments/m75lt7/my_current_favorite_feature_of_emacs/

for documentation, this was my process for making above video:
  1. ``brew install obs``
  2. launch obs, choose window capture for emacs
  3. press record, do something cool in symex
  4. convert video to mp4 ``ffmpeg -i ~/Videos/something.mkv -c copy out.mp4``
  5. upload

**Comment by countvajhula** [comment]
Right on, I have been meaning to make some animations, I just haven't gotten around to it yet. But now that a 1.0 release is out, I will make time to do it sometime soon 😄 . Thanks for sharing your process!

Incidentally, in Emacs I use the undotree functionality only occasionally, but in Vim I use it all the time. The difference is that in Vim the undo feature is rock solid, whereas in Emacs, as many have reported, undotree occasionally loses data. Maybe just once for every few hundred or even thousand undo operations, but, that tiny bit of unreliability turns out to make a huge difference in how often I use it. It's made [a lot of progress](https://www.dr-qubit.org/Lost_undo-tree_history.html) recently though, so I am hopeful that the feature will eventually be fixed.

**Comment by tommy-mor** [comment]
I have not used it extensively so I did not know about that issue, seems like people in the reddit also have this problem. 

I will be getting back into clojure in the coming weeks, so I will also be learning symex. Once I get into it I will make a gif if I ever notice I do something slick (like I did with the reddit post). kind of like highlight reel of interesting plays in a videogame, inspired by emacs-rocks and csgo highlight reels

**Comment by countvajhula** [comment]
Sweet, looking forward to it, and enjoy your return to Clojure!

**Comment by countvajhula** [comment]
@tommy-mor This took... a while to make. But I finally put it up, [take a look](https://countvajhula.com/2021/09/25/the-animated-guide-to-symex/)! Also don't miss the linked [introductory post](https://countvajhula.com/2021/09/25/symex-el-edit-lisp-code-in-a-vim-like-way/) 😉

**Comment by tommy-mor** [comment]
awesome! great article.
